# Generated by Django 3.2.9 on 2021-12-22 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(to='projeto.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=4096)),
                ('images', models.CharField(max_length=100)),
                ('is_login_required', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.user')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='id_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.user'),
        ),
    ]
